#!/usr/bin/env python3
"""Generate web_ui_gz.h (gzip-compressed web UI) from web_ui.h.

Reads the INDEX_HTML raw literal from web_ui.h and writes web_ui_gz.h with:
  - INDEX_HTML_GZ: the page gzip-compressed bytes stored in PROGMEM
  - INDEX_HTML_GZ_LEN: compressed length
  - INDEX_HTML_ETAG: stable content hash used for HTTP caching (304 replies)

Usage:
  Python: python3 tools/gen_web_gzip.py               (uses defaults below)
  Flows:  release.sh calls this automatically; run it by hand whenever you
          edit web_ui.h and want to flash without going through a release.
"""
import argparse
import gzip
import hashlib
import os
import re

DEFAULTS = {
    "input": "Firmware/petalot/web_ui.h",
    "output": "Firmware/petalot/web_ui_gz.h",
}
RAW_RE = re.compile(r'R"rawliteral\((.*)\)rawliteral";', re.S)


def extract(inp):
    src = open(inp, "r", encoding="utf-8").read()
    m = RAW_RE.search(src)
    if not m:
        raise SystemExit(f"error: no R\"rawliteral(...)\" payload found in {inp}")
    return m.group(1)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input", default=DEFAULTS["input"])
    p.add_argument("--output", default=DEFAULTS["output"])
    args = p.parse_args()

    payload = extract(args.input).encode("utf-8")
    # gzip.compress with mtime=0 so the output is byte-for-byte reproducible.
    gz = gzip.compress(payload, mtime=0)
    etag = '"{}"'.format(hashlib.md5(gz).hexdigest()[:16])

    lines = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "// AUTO-GENERATED by gen_web_gzip.py - do not edit.",
        "// Regenerate after any change to web_ui.h:",
        "//   python3 Firmware/tools/gen_web_gzip.py",
        "//",
        f"// Source: {os.path.basename(args.input)} ({len(payload)} bytes raw)",
        f"// gzip-compressed to {len(gz)} bytes",
        "",
        "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {",
        _fmt_bytes(gz),
        "};",
        "",
        f"static const uint16_t INDEX_HTML_GZ_LEN = {len(gz)};",
        f"static const char INDEX_HTML_ETAG[] PROGMEM = {etag};",
        "",
    ]
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(
        f"wrote {args.output}: {len(payload)} -> {len(gz)} bytes "
        f"(gzip, {(1 - len(gz) / len(payload)) * 100:.0f}% smaller), ETag {etag}"
    )


def _fmt_bytes(data, per_line=16):
    parts = [f"  0x{b:02x}," for b in data]
    return "\n".join(
        "  " + " ".join(parts[i : i + per_line]) for i in range(0, len(parts), per_line)
    )


if __name__ == "__main__":
    main()